---
name: 'Conventional Commits'
# Author:       Casey Sparks
# Date:         August 22, 2024
# Description:  Ensures that commit titles adhere to the Conventional Commit syntax.
# Ref:          See https://www.conventionalcommits.org/en/v1.0.0/

on:
  pull_request:
    branches: ['main']
jobs:
  check_commit_names:
    name: 'Conventional Commits'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@11bd719'                                        # v4.2.2

      - name: 'Validate commits'
        uses: 'webiny/action-conventional-commits@8bc41ff'                      # v1.3.0
        with:
          GITHUB_TOKEN: '${{ github.token }}'
...
