---
name: 'Conventional Pull Request Titles'
# Author:       Casey Sparks
# Date:         September 03, 2024
# Description:  Ensure that Pull Request title adheres to the conventional commit syntax.
# Ref:          https://github.com/amannn/action-semantic-pull-request

on:
  pull_request_target:
    types:
      - 'edited'
      - 'opened'
      - 'reopened'
      - 'synchronize'
permissions:
  pull-requests: 'read'
jobs:
  conventional_pull_request:
    name: 'Validate Pull Request Title'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Validate pull request title'
        uses: 'amannn/action-semantic-pull-request@0723387'                     # v5.5.3
        env:
          GITHUB_TOKEN: '${{ github.token }}'
        with:
          types: |
            fix
            feat
            build
            chore
            ci
            docs
            style
            refactor
            perf
            test
          requireScope: true
          scopes: |                                                             # Regex auto-wrapped in `^ $`.
            .*
          ignoreLabels: |
            bot
            ignore-semantic-pull-request
          headerPattern: '^(\w*)(?:\(([\w$.\-*/ ]*)\))?: (.*)$'
          headerPatternCorrespondence: 'type, scope, subject'
...
