---
name: 'Validate Python code'
# Author:       Casey Sparks
# Date:         November 15, 2023
# Description:  Lint all Python files with both Pylint and Flake8.

on:
  pull_request:
    branches: ['main']
    paths: ['**/*.py']
env:
  PY_VER: '3.11'
  PY_MAX_LINES: 120
jobs:
  flake8:
    name: 'flake8'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@11bd719'                                        # v4.2.2
        with:
          fetch-depth: 0

      - name: 'Get changed files'
        id: 'changed_files'
        uses: 'tj-actions/changed-files@c3a1bb2'                                # v45.0.3
        with:
          files: '**.py'

      - name: 'Set up Python environment'
        uses: 'actions/setup-python@0b93645'                                    # v5.3.0
        with:
          python-version: '${{ env.PY_VER }}'

      - name: 'flake8 lint'
        uses: 'py-actions/flake8@84ec672'                                       # v2.3.0
        with:
          max-line-length: '${{ env.PY_MAX_LINES }}'
          path: '${{ steps.changed_files.outputs.all_changed_files }}'

  pylint:
    name: 'pylint'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@11bd719'                                        # v4.2.2
        with:
          fetch-depth: 0

      - name: 'Set up Python ${{ env.PY_VER }}'
        uses: 'actions/setup-python@0b93645'                                    # v5.3.0
        with:
          python-version: '${{ env.PY_VER }}'

      - name: 'Install dependencies'
        run: |
          for FILE in $(find ./ -name requirements.txt -type f); do
            python -m pip install                                           \
              --no-cache-dir                                                \
              --requirement                                                 \
              "${FILE}"
          done

      - name: 'Install PyLint'
        run: >
          python -m pip install pylint

      - name: 'Get changed files'
        id: 'changed_files'
        uses: 'tj-actions/changed-files@c3a1bb2'                                # v45.0.3
        with:
          files: '**.py'

      - name: 'Lint Python scripts with PyLint'
        run: >
          pylint
            --recursive yes
            --max-line-length ${{ env.PY_MAX_LINES }}
            --disable logging-fstring-interpolation
            ${{ steps.changed_files.outputs.all_changed_files }}
...
